package mods.storemore;

import net.minecraft.item.ItemStack;

public class sm_ItemStacks extends StoreMore{


	public static ItemStack dirtI,dirtII,dirtIII,dirtIV,dirtV,dirtVI,dirtVII,dirtVIII;
	public static ItemStack cobbleI,cobbleII,cobbleIII,cobbleIV,cobbleV,cobbleVI,cobbleVII,cobbleVIII;
	public static ItemStack stoneI,stoneII,stoneIII,stoneIV,stoneV,stoneVI,stoneVII,stoneVIII;
	public static ItemStack gravelI,gravelII,gravelIII,gravelIV,gravelV,gravelVI,gravelVII,gravelVIII;
	public static ItemStack sandI,sandII,sandIII,sandIV,sandV,sandVI,sandVII,sandVIII;
	public static ItemStack sandstoneI,sandstoneII,sandstoneIII,sandstoneIV,sandstoneV,sandstoneVI,sandstoneVII,sandstoneVIII;
	public static ItemStack obsidianI,obsidianII,obsidianIII,obsidianIV;
	public static ItemStack glowstoneI,glowstoneII,glowstoneIII,glowstoneIV;
	public static ItemStack netherrackI,netherrackII,netherrackIII,netherrackIV;
	public static ItemStack ironI,ironII,ironIII,ironIV;
	public static ItemStack goldI,goldII,goldIII,goldIV;
	public static ItemStack diamondI,diamondII,diamondIII,diamondIV;
	public static ItemStack emeraldI,emeraldII,emeraldIII,emeraldIV;
	public static ItemStack sticksI,sticksII,sticksIII,sticksIV;
	public static ItemStack torchesI,torchesII,torchesIII,torchesIV;
	public static ItemStack gunpowderI,gunpowderII,gunpowderIII,gunpowderIV;
	public static ItemStack flintI,flintII,flintIII,flintIV;
	public static ItemStack oakwoodI,oakwoodII,oakwoodIII,oakwoodIV;
	public static ItemStack sprucewoodI,sprucewoodII,sprucewoodIII,sprucewoodIV;
	public static ItemStack birchwoodI,birchwoodII,birchwoodIII,birchwoodIV;
	public static ItemStack junglewoodI,junglewoodII,junglewoodIII,junglewoodIV;
	public static ItemStack oakplanksI,oakplanksII,oakplanksIII,oakplanksIV;
	public static ItemStack spruceplanksI,spruceplanksII,spruceplanksIII,spruceplanksIV;
	public static ItemStack birchplanksI,birchplanksII,birchplanksIII,birchplanksIV;
	public static ItemStack jungleplanksI,jungleplanksII,jungleplanksIII,jungleplanksIV;
	public static ItemStack glassI,glassII,glassIII,glassIV;
	public static ItemStack redstoneI,redstoneII,redstoneIII,redstoneIV;
	public static ItemStack quartzI,quartzII,quartzIII,quartzIV;
	public static ItemStack clayI,clayII,clayIII,clayIV;
	public static ItemStack soulsandI,soulsandII,soulsandIII,soulsandIV;
	public static ItemStack appleI,appleII,appleIII,appleIV;
	public static ItemStack goldappleI,goldappleII,goldappleIII,goldappleIV;
	public static ItemStack rawbeefI,rawbeefII,rawbeefIII,rawbeefIV;
	public static ItemStack cookedbeefI,cookedbeefII,cookedbeefIII,cookedbeefIV;
	public static ItemStack breadI,breadII,breadIII,breadIV;
	public static ItemStack cakeI,cakeII,cakeIII,cakeIV;
	public static ItemStack carrotI,carrotII,carrotIII,carrotIV;
	public static ItemStack goldcarrotI,goldcarrotII,goldcarrotIII,goldcarrotIV;
	public static ItemStack rawchickenI,rawchickenII,rawchickenIII,rawchickenIV;
	public static ItemStack cookedchickenI,cookedchickenII,cookedchickenIII,cookedchickenIV;
	public static ItemStack eggI,eggII,eggIII,eggIV;
	public static ItemStack cookiesI,cookiesII,cookiesIII,cookiesIV;
	public static ItemStack sugarI,sugarII,sugarIII,sugarIV;
	public static ItemStack potatoI,potatoII,potatoIII,potatoIV;
	public static ItemStack bpotatoI,bpotatoII,bpotatoIII,bpotatoIV;
	public static ItemStack ppotatoI,ppotatoII,ppotatoIII,ppotatoIV;
	public static ItemStack rawfishI,rawfishII,rawfishIII,rawfishIV;
	public static ItemStack cookedfishI,cookedfishII,cookedfishIII,cookedfishIV;
	public static ItemStack rawporkI,rawporkII,rawporkIII,rawporkIV;
	public static ItemStack cookedporkI,cookedporkII,cookedporkIII,cookedporkIV;
	public static ItemStack coalI,coalII,coalIII,coalIV;
	public static ItemStack charcoalI,charcoalII,charcoalIII,charcoalIV;

	public static ItemStack superCompressor;
	

	{
		cobbleI = new ItemStack(StoreMore.packedblocksI, 1, 0);
		cobbleII = new ItemStack(StoreMore.packedblocksI, 1, 1);
		cobbleIII = new ItemStack(StoreMore.packedblocksI, 1, 2);
		cobbleIV = new ItemStack(StoreMore.packedblocksI, 1, 3);
		cobbleV = new ItemStack(StoreMore.packedblocksI, 1, 4);
		cobbleVI = new ItemStack(StoreMore.packedblocksI, 1, 5);
		cobbleVII = new ItemStack(StoreMore.packedblocksI, 1, 6);
		cobbleVIII = new ItemStack(StoreMore.packedblocksI, 1, 7);
		stoneI = new ItemStack(StoreMore.packedblocksI, 1, 8);
		stoneII = new ItemStack(StoreMore.packedblocksI, 1, 9);
		stoneIII = new ItemStack(StoreMore.packedblocksI, 1, 10);
		stoneIV = new ItemStack(StoreMore.packedblocksI, 1, 11);
		stoneV = new ItemStack(StoreMore.packedblocksI, 1, 12);
		stoneVI = new ItemStack(StoreMore.packedblocksI, 1, 13);
		stoneVII = new ItemStack(StoreMore.packedblocksI, 1, 14);
		stoneVIII = new ItemStack(StoreMore.packedblocksI, 1, 15);
		dirtI = new ItemStack(StoreMore.packedblocksII, 1, 0);
		dirtII = new ItemStack(StoreMore.packedblocksII, 1, 1);
		dirtIII = new ItemStack(StoreMore.packedblocksII, 1, 2);
		dirtIV = new ItemStack(StoreMore.packedblocksII, 1, 3);
		dirtV = new ItemStack(StoreMore.packedblocksII, 1, 4);
		dirtVI = new ItemStack(StoreMore.packedblocksII, 1, 5);
		dirtVII = new ItemStack(StoreMore.packedblocksII, 1, 6);
		dirtVIII = new ItemStack(StoreMore.packedblocksII, 1, 7);
		gravelI = new ItemStack(StoreMore.packedblocksII, 1, 8);
		gravelII = new ItemStack(StoreMore.packedblocksII, 1, 9);
		gravelIII = new ItemStack(StoreMore.packedblocksII, 1, 10);
		gravelIV = new ItemStack(StoreMore.packedblocksII, 1, 11);
		gravelV = new ItemStack(StoreMore.packedblocksII, 1, 12);
		gravelVI = new ItemStack(StoreMore.packedblocksII, 1, 13);
		gravelVII = new ItemStack(StoreMore.packedblocksII, 1, 14);
		gravelVIII = new ItemStack(StoreMore.packedblocksII, 1, 15);
		sandI = new ItemStack(StoreMore.packedblocksIII, 1, 0);
		sandII = new ItemStack(StoreMore.packedblocksIII, 1, 1);
		sandIII = new ItemStack(StoreMore.packedblocksIII, 1, 2);
		sandIV = new ItemStack(StoreMore.packedblocksIII, 1, 3);
		sandV = new ItemStack(StoreMore.packedblocksIII, 1, 4);
		sandVI = new ItemStack(StoreMore.packedblocksIII, 1, 5);
		sandVII = new ItemStack(StoreMore.packedblocksIII, 1, 6);
		sandVIII = new ItemStack(StoreMore.packedblocksIII, 1, 7);
		sandstoneI = new ItemStack(StoreMore.packedblocksIII, 1, 8);
		sandstoneII = new ItemStack(StoreMore.packedblocksIII, 1, 9);
		sandstoneIII = new ItemStack(StoreMore.packedblocksIII, 1, 10);
		sandstoneIV = new ItemStack(StoreMore.packedblocksIII, 1, 11);
		sandstoneV = new ItemStack(StoreMore.packedblocksIII, 1, 12);
		sandstoneVI = new ItemStack(StoreMore.packedblocksIII, 1, 13);
		sandstoneVII = new ItemStack(StoreMore.packedblocksIII, 1, 14);
		sandstoneVIII = new ItemStack(StoreMore.packedblocksIII, 1, 15);
		obsidianI = new ItemStack(StoreMore.packedblocksIV, 1, 0);
		obsidianII = new ItemStack(StoreMore.packedblocksIV, 1, 1);
		obsidianIII = new ItemStack(StoreMore.packedblocksIV, 1, 2);
		obsidianIV = new ItemStack(StoreMore.packedblocksIV, 1, 3);
		glowstoneI = new ItemStack(StoreMore.packedblocksIV, 1, 4);
		glowstoneII = new ItemStack(StoreMore.packedblocksIV, 1, 5);
		glowstoneIII = new ItemStack(StoreMore.packedblocksIV, 1, 6);
		glowstoneIV = new ItemStack(StoreMore.packedblocksIV, 1, 7);
		netherrackI = new ItemStack(StoreMore.packedblocksIV, 1, 8);
		netherrackII = new ItemStack(StoreMore.packedblocksIV, 1, 9);
		netherrackIII = new ItemStack(StoreMore.packedblocksIV, 1, 10);
		netherrackIV = new ItemStack(StoreMore.packedblocksIV, 1, 11);
		ironI = new ItemStack(StoreMore.packedblocksV, 1, 0);
		ironII = new ItemStack(StoreMore.packedblocksV, 1, 1);
		ironIII = new ItemStack(StoreMore.packedblocksV, 1, 2);
		ironIV = new ItemStack(StoreMore.packedblocksV, 1, 3);
		goldI = new ItemStack(StoreMore.packedblocksV, 1, 4);
		goldII = new ItemStack(StoreMore.packedblocksV, 1, 5);
		goldIII = new ItemStack(StoreMore.packedblocksV, 1, 6);
		goldIV = new ItemStack(StoreMore.packedblocksV, 1, 7);
		diamondI = new ItemStack(StoreMore.packedblocksV, 1, 8);
		diamondII = new ItemStack(StoreMore.packedblocksV, 1, 9);
		diamondIII = new ItemStack(StoreMore.packedblocksV, 1, 10);
		diamondIV = new ItemStack(StoreMore.packedblocksV, 1, 11);
		emeraldI = new ItemStack(StoreMore.packedblocksV, 1, 12);
		emeraldII = new ItemStack(StoreMore.packedblocksV, 1, 13);
		emeraldIII = new ItemStack(StoreMore.packedblocksV, 1, 14);
		emeraldIV = new ItemStack(StoreMore.packedblocksV, 1, 15);
		sticksI = new ItemStack(StoreMore.packedblocksVI, 1, 0);
		sticksII = new ItemStack(StoreMore.packedblocksVI, 1, 1);
		sticksIII = new ItemStack(StoreMore.packedblocksVI, 1, 2);
		sticksIV = new ItemStack(StoreMore.packedblocksVI, 1, 3);
		torchesI = new ItemStack(StoreMore.packedblocksVI, 1, 4);
		torchesII = new ItemStack(StoreMore.packedblocksVI, 1, 5);
		torchesIII = new ItemStack(StoreMore.packedblocksVI, 1, 6);
		torchesIV = new ItemStack(StoreMore.packedblocksVI, 1, 7);
		gunpowderI = new ItemStack(StoreMore.packedblocksVI, 1, 8);
		gunpowderII = new ItemStack(StoreMore.packedblocksVI, 1, 9);
		gunpowderIII = new ItemStack(StoreMore.packedblocksVI, 1, 10);
		gunpowderIV = new ItemStack(StoreMore.packedblocksVI, 1, 11);
		flintI = new ItemStack(StoreMore.packedblocksVI, 1, 12);
		flintII = new ItemStack(StoreMore.packedblocksVI, 1, 13);
		flintIII = new ItemStack(StoreMore.packedblocksVI, 1, 14);
		flintIV = new ItemStack(StoreMore.packedblocksVI, 1, 15);
		oakwoodI = new ItemStack(StoreMore.packedblocksVII, 1, 0);
		oakwoodII = new ItemStack(StoreMore.packedblocksVII, 1, 1);
		oakwoodIII = new ItemStack(StoreMore.packedblocksVII, 1, 2);
		oakwoodIV = new ItemStack(StoreMore.packedblocksVII, 1, 3);
		sprucewoodI = new ItemStack(StoreMore.packedblocksVII, 1, 4);
		sprucewoodII = new ItemStack(StoreMore.packedblocksVII, 1, 5);
		sprucewoodIII = new ItemStack(StoreMore.packedblocksVII, 1, 6);
		sprucewoodIV = new ItemStack(StoreMore.packedblocksVII, 1, 7);
		birchwoodI = new ItemStack(StoreMore.packedblocksVII, 1, 8);
		birchwoodII = new ItemStack(StoreMore.packedblocksVII, 1, 9);
		birchwoodIII = new ItemStack(StoreMore.packedblocksVII, 1, 10);
		birchwoodIV = new ItemStack(StoreMore.packedblocksVII, 1, 11);
		junglewoodI = new ItemStack(StoreMore.packedblocksVII, 1, 12);
		junglewoodII = new ItemStack(StoreMore.packedblocksVII, 1, 13);
		junglewoodIII = new ItemStack(StoreMore.packedblocksVII, 1, 14);
		junglewoodIV = new ItemStack(StoreMore.packedblocksVII, 1, 15);
		oakplanksI = new ItemStack(StoreMore.packedblocksVIII, 1, 0);
		oakplanksII = new ItemStack(StoreMore.packedblocksVIII, 1, 1);
		oakplanksIII = new ItemStack(StoreMore.packedblocksVIII, 1, 2);
		oakplanksIV = new ItemStack(StoreMore.packedblocksVIII, 1, 3);
		spruceplanksI = new ItemStack(StoreMore.packedblocksVIII, 1, 4);
		spruceplanksII = new ItemStack(StoreMore.packedblocksVIII, 1, 5);
		spruceplanksIII = new ItemStack(StoreMore.packedblocksVIII, 1, 6);
		spruceplanksIV = new ItemStack(StoreMore.packedblocksVIII, 1, 7);
		birchplanksI = new ItemStack(StoreMore.packedblocksVIII, 1, 8);
		birchplanksII = new ItemStack(StoreMore.packedblocksVIII, 1, 9);
		birchplanksIII = new ItemStack(StoreMore.packedblocksVIII, 1, 10);
		birchplanksIV = new ItemStack(StoreMore.packedblocksVIII, 1, 11);
		jungleplanksI = new ItemStack(StoreMore.packedblocksVIII, 1, 12);
		jungleplanksII = new ItemStack(StoreMore.packedblocksVIII, 1, 13);
		jungleplanksIII = new ItemStack(StoreMore.packedblocksVIII, 1, 14);
		jungleplanksIV = new ItemStack(StoreMore.packedblocksVIII, 1, 15);
		glassI = new ItemStack(StoreMore.packedglass, 1, 0);
		glassII = new ItemStack(StoreMore.packedglass, 1, 1);
		glassIII = new ItemStack(StoreMore.packedglass, 1, 2);
		glassIV = new ItemStack(StoreMore.packedglass, 1, 3);
		coalI = new ItemStack(StoreMore.packedcoalI, 1, 0);
		coalII = new ItemStack(StoreMore.packedcoalII, 1, 0);
		coalIII = new ItemStack(StoreMore.packedcoalIII, 1, 0);
		coalIV = new ItemStack(StoreMore.packedcoalIV, 1, 0);
		charcoalI = new ItemStack(StoreMore.packedcharcoalI, 1, 0);
		charcoalII = new ItemStack(StoreMore.packedcharcoalII, 1, 0);
		charcoalIII = new ItemStack(StoreMore.packedcharcoalIII, 1, 0);
		charcoalIV = new ItemStack(StoreMore.packedcharcoalIV, 1, 0);
		redstoneI = new ItemStack(StoreMore.packedblocksIX, 1, 0);
		redstoneII = new ItemStack(StoreMore.packedblocksIX, 1, 1);
		redstoneIII = new ItemStack(StoreMore.packedblocksIX, 1, 2);
		redstoneIV = new ItemStack(StoreMore.packedblocksIX, 1, 3);
		quartzI = new ItemStack(StoreMore.packedblocksIX, 1, 4);
		quartzII = new ItemStack(StoreMore.packedblocksIX, 1, 5);
		quartzIII = new ItemStack(StoreMore.packedblocksIX, 1, 6);
		quartzIV = new ItemStack(StoreMore.packedblocksIX, 1, 7);
		soulsandI = new ItemStack(StoreMore.packedblocksIX, 1, 8);
		soulsandII = new ItemStack(StoreMore.packedblocksIX, 1, 9);
		soulsandIII = new ItemStack(StoreMore.packedblocksIX, 1, 10);
		soulsandIV = new ItemStack(StoreMore.packedblocksIX, 1, 11);
		clayI = new ItemStack(StoreMore.packedblocksIX, 1, 12);
		clayII = new ItemStack(StoreMore.packedblocksIX, 1, 13);
		clayIII = new ItemStack(StoreMore.packedblocksIX, 1, 14);
		clayIV = new ItemStack(StoreMore.packedblocksIX, 1, 15);
		appleI = new ItemStack(StoreMore.packedfoodI, 1, 0);
		appleII = new ItemStack(StoreMore.packedfoodI, 1, 1);
		appleIII = new ItemStack(StoreMore.packedfoodI, 1, 2);
		appleIV = new ItemStack(StoreMore.packedfoodI, 1, 3);
		goldappleI = new ItemStack(StoreMore.packedfoodI, 1, 4);
		goldappleII = new ItemStack(StoreMore.packedfoodI, 1, 5);
		goldappleIII = new ItemStack(StoreMore.packedfoodI, 1, 6);
		goldappleIV = new ItemStack(StoreMore.packedfoodI, 1, 7);
		rawbeefI = new ItemStack(StoreMore.packedfoodI, 1, 8);
		rawbeefII = new ItemStack(StoreMore.packedfoodI, 1, 9);
		rawbeefIII = new ItemStack(StoreMore.packedfoodI, 1, 10);
		rawbeefIV = new ItemStack(StoreMore.packedfoodI, 1, 11);
		cookedbeefI = new ItemStack(StoreMore.packedfoodI, 1, 12);
		cookedbeefII = new ItemStack(StoreMore.packedfoodI, 1, 13);
		cookedbeefIII = new ItemStack(StoreMore.packedfoodI, 1, 14);
		cookedbeefIV = new ItemStack(StoreMore.packedfoodI, 1, 15);
		breadI = new ItemStack(StoreMore.packedfoodII, 1, 0);
		breadII = new ItemStack(StoreMore.packedfoodII, 1, 1);
		breadIII = new ItemStack(StoreMore.packedfoodII, 1, 2);
		breadIV = new ItemStack(StoreMore.packedfoodII, 1, 3);
		cakeI = new ItemStack(StoreMore.packedfoodII, 1, 4);
		cakeII = new ItemStack(StoreMore.packedfoodII, 1, 5);
		cakeIII = new ItemStack(StoreMore.packedfoodII, 1, 6);
		cakeIV = new ItemStack(StoreMore.packedfoodII, 1, 7);
		carrotI = new ItemStack(StoreMore.packedfoodII, 1, 8);
		carrotII = new ItemStack(StoreMore.packedfoodII, 1, 9);
		carrotIII = new ItemStack(StoreMore.packedfoodII, 1, 10);
		carrotIV = new ItemStack(StoreMore.packedfoodII, 1, 11);
		goldcarrotI = new ItemStack(StoreMore.packedfoodII, 1, 12);
		goldcarrotII = new ItemStack(StoreMore.packedfoodII, 1, 13);
		goldcarrotIII = new ItemStack(StoreMore.packedfoodII, 1, 14);
		goldcarrotIV = new ItemStack(StoreMore.packedfoodII, 1, 15);
		rawchickenI = new ItemStack(StoreMore.packedfoodIII, 1, 0);
		rawchickenII = new ItemStack(StoreMore.packedfoodIII, 1, 1);
		rawchickenIII = new ItemStack(StoreMore.packedfoodIII, 1, 2);
		rawchickenIV = new ItemStack(StoreMore.packedfoodIII, 1, 3);
		cookedchickenI = new ItemStack(StoreMore.packedfoodIII, 1, 4);
		cookedchickenII = new ItemStack(StoreMore.packedfoodIII, 1, 5);
		cookedchickenIII = new ItemStack(StoreMore.packedfoodIII, 1, 6);
		cookedchickenIV = new ItemStack(StoreMore.packedfoodIII, 1, 7);
		cookiesI = new ItemStack(StoreMore.packedfoodIII, 1, 8);
		cookiesII = new ItemStack(StoreMore.packedfoodIII, 1, 9);
		cookiesIII = new ItemStack(StoreMore.packedfoodIII, 1, 10);
		cookiesIV = new ItemStack(StoreMore.packedfoodIII, 1, 11);
		eggI = new ItemStack(StoreMore.packedfoodIII, 1, 12);
		eggII = new ItemStack(StoreMore.packedfoodIII, 1, 13);
		eggIII = new ItemStack(StoreMore.packedfoodIII, 1, 14);
		eggIV = new ItemStack(StoreMore.packedfoodIII, 1, 15);
		sugarI = new ItemStack(StoreMore.packedfoodIV, 1, 0);
		sugarII = new ItemStack(StoreMore.packedfoodIV, 1, 1);
		sugarIII = new ItemStack(StoreMore.packedfoodIV, 1, 2);
		sugarIV = new ItemStack(StoreMore.packedfoodIV, 1, 3);
		potatoI = new ItemStack(StoreMore.packedfoodIV, 1, 4);
		potatoII = new ItemStack(StoreMore.packedfoodIV, 1, 5);
		potatoIII = new ItemStack(StoreMore.packedfoodIV, 1, 6);
		potatoIV = new ItemStack(StoreMore.packedfoodIV, 1, 7);
		bpotatoI = new ItemStack(StoreMore.packedfoodIV, 1, 8);
		bpotatoII = new ItemStack(StoreMore.packedfoodIV, 1, 9);
		bpotatoIII = new ItemStack(StoreMore.packedfoodIV, 1, 10);
		bpotatoIV = new ItemStack(StoreMore.packedfoodIV, 1, 11);
		ppotatoI = new ItemStack(StoreMore.packedfoodIV, 1, 12);
		ppotatoII = new ItemStack(StoreMore.packedfoodIV, 1, 13);
		ppotatoIII = new ItemStack(StoreMore.packedfoodIV, 1, 14);
		ppotatoIV = new ItemStack(StoreMore.packedfoodIV, 1, 15);
		rawfishI = new ItemStack(StoreMore.packedfoodV, 1, 0);
		rawfishII = new ItemStack(StoreMore.packedfoodV, 1, 1);
		rawfishIII = new ItemStack(StoreMore.packedfoodV, 1, 2);
		rawfishIV = new ItemStack(StoreMore.packedfoodV, 1, 3);
		cookedfishI = new ItemStack(StoreMore.packedfoodV, 1, 4);
		cookedfishII = new ItemStack(StoreMore.packedfoodV, 1, 5);
		cookedfishIII = new ItemStack(StoreMore.packedfoodV, 1, 6);
		cookedfishIV = new ItemStack(StoreMore.packedfoodV, 1, 7);
		rawporkI = new ItemStack(StoreMore.packedfoodV, 1, 8);
		rawporkII = new ItemStack(StoreMore.packedfoodV, 1, 9);
		rawporkIII = new ItemStack(StoreMore.packedfoodV, 1, 10);
		rawporkIV = new ItemStack(StoreMore.packedfoodV, 1, 11);
		cookedporkI = new ItemStack(StoreMore.packedfoodV, 1, 12);
		cookedporkII = new ItemStack(StoreMore.packedfoodV, 1, 13);
		cookedporkIII = new ItemStack(StoreMore.packedfoodV, 1, 14);
		cookedporkIV = new ItemStack(StoreMore.packedfoodV, 1, 15);


		superCompressor = new ItemStack(StoreMore.BlockSuperCompressor);
	}

	

}
