package mods.storemore;

import mods.storemore.ic2.sm_ic2plugin;
import net.minecraft.item.ItemStack;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class sm_naming {
	
	public static void init()
    { 
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 0), "Packed Cobblestone I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 1), "Packed Cobblestone II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 2), "Packed Cobblestone III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 3), "Packed Cobblestone IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 4), "Packed Cobblestone V");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 5), "Packed Cobblestone VI");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 6), "Packed Cobblestone VII");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 7), "Packed Cobblestone VIII");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 8), "Packed Stone I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 9), "Packed Stone II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 10), "Packed Stone III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 11), "Packed Stone IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 12), "Packed Stone V");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 13), "Packed Stone VI");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 14), "Packed Stone VII");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksI, 1, 15), "Packed Stone VIII");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 0), "Packed Dirt I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 1), "Packed Dirt II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 2), "Packed Dirt III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 3), "Packed Dirt IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 4), "Packed Dirt V");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 5), "Packed Dirt VI");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 6), "Packed Dirt VII");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 7), "Packed Dirt VIII");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 8), "Packed Gravel I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 9), "Packed Gravel II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 10), "Packed Gravel III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 11), "Packed Gravel IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 12), "Packed Gravel V");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 13), "Packed Gravel VI");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 14), "Packed Gravel VII");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksII, 1, 15), "Packed Gravel VIII");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 0), "Packed Sand I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 1), "Packed Sand II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 2), "Packed Sand III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 3), "Packed Sand IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 4), "Packed Sand V");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 5), "Packed Sand VI");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 6), "Packed Sand VII");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 7), "Packed Sand VIII");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 8), "Packed Sandstone I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 9), "Packed Sandstone II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 10), "Packed Sandstone III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 11), "Packed Sandstone IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 12), "Packed Sandstone V");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 13), "Packed Sandstone VI");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 14), "Packed Sandstone VII");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIII, 1, 15), "Packed Sandstone VIII");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIV, 1, 0), "Packed Obsidian I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIV, 1, 1), "Packed Obsidian II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIV, 1, 2), "Packed Obsidian III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIV, 1, 3), "Packed Obsidian IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIV, 1, 4), "Packed Glowstone I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIV, 1, 5), "Packed Glowstone II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIV, 1, 6), "Packed Glowstone III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIV, 1, 7), "Packed Glowstone IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIV, 1, 8), "Packed Netherrack I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIV, 1, 9), "Packed Netherrack II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIV, 1, 10), "Packed Netherrack III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIV, 1, 11), "Packed Netherrack IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 0), "Packed Iron I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 1), "Packed Iron II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 2), "Packed Iron III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 3), "Packed Iron IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 4), "Packed Gold I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 5), "Packed Gold II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 6), "Packed Gold III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 7), "Packed Gold IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 8), "Packed Diamond I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 9), "Packed Diamond II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 10), "Packed Diamond III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 11), "Packed Diamond IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 12), "Packed Emerald I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 13), "Packed Emerald II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 14), "Packed Emerald III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksV, 1, 15), "Packed Emerald IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 0), "Packed Sticks I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 1), "Packed Sticks II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 2), "Packed Sticks III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 3), "Packed Sticks IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 4), "Packed Torches I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 5), "Packed Torches II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 6), "Packed Torches III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 7), "Packed Torches IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 8), "Packed Gunpowder I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 9), "Packed Gunpowder II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 10), "Packed Gunpowder III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 11), "Packed Gunpowder IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 12), "Packed Flint I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 13), "Packed Flint II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 14), "Packed Flint III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVI, 1, 15), "Packed Flint IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 0), "Packed Oak Wood I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 1), "Packed Oak Wood II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 2), "Packed Oak Wood III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 3), "Packed Oak Wood IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 4), "Packed Spruce Wood I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 5), "Packed Spruce Wood II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 6), "Packed Spruce Wood III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 7), "Packed Spruce Wood IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 8), "Packed Birch Wood I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 9), "Packed Birch Wood II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 10), "Packed Birch Wood III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 11), "Packed Birch Wood IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 12), "Packed Jungle Wood I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 13), "Packed Jungle Wood II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 14), "Packed Jungle Wood III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVII, 1, 15), "Packed Jungle Wood IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 0), "Packed Oak Planks I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 1), "Packed Oak Planks II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 2), "Packed Oak Planks III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 3), "Packed Oak Planks IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 4), "Packed Spruce Planks I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 5), "Packed Spruce Planks II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 6), "Packed Spruce Planks III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 7), "Packed Spruce Planks IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 8), "Packed Birch Planks I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 9), "Packed Birch Planks II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 10), "Packed Birch Planks III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 11), "Packed Birch Planks IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 12), "Packed Jungle Planks I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 13), "Packed Jungle Planks II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 14), "Packed Jungle Planks III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksVIII, 1, 15), "Packed Jungle Planks IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedglass, 1, 0), "Packed Glass I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedglass, 1, 1), "Packed Glass II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedglass, 1, 2), "Packed Glass III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedglass, 1, 3), "Packed Glass IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedcoalI, 1, 0), "Packed Coal I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedcoalII, 1, 0), "Packed Coal II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedcoalIII, 1, 0), "Packed Coal III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedcoalIV, 1, 0), "Packed Coal IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedcharcoalI, 1, 0), "Packed Charcoal I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedcharcoalII, 1, 0), "Packed Charcoal II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedcharcoalIII, 1, 0), "Packed Charcoal III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedcharcoalIV, 1, 0), "Packed Charcoal IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 0), "Packed Redstone I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 1), "Packed Redstone II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 2), "Packed Redstone III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 3), "Packed Redstone IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 4), "Packed Quartz I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 5), "Packed Quartz II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 6), "Packed Quartz III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 7), "Packed Quartz IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 8), "Packed Soulsand I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 9), "Packed Soulsand II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 10), "Packed Soulsand III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 11), "Packed Soulsand IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 12), "Packed Clay I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 13), "Packed Clay II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 14), "Packed Clay III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedblocksIX, 1, 15), "Packed Clay IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 0), "Packed Red Apple I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 1), "Packed Red Apple II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 2), "Packed Red Apple III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 3), "Packed Red Apple IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 4), "Packed Gold Apple I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 5), "Packed Gold Apple II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 6), "Packed Gold Apple III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 7), "Packed Gold Apple IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 8), "Packed Raw Beef I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 9), "Packed Raw Beef II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 10), "Packed Raw Beef III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 11), "Packed Raw Beef IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 12), "Packed Cooked Beef I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 13), "Packed Cooked Beef II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 14), "Packed Cooked Beef III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodI, 1, 15), "Packed Cooked Beef IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 0), "Packed Bread I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 1), "Packed Bread II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 2), "Packed Bread III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 3), "Packed Bread IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 4), "Packed Cake I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 5), "Packed Cake II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 6), "Packed Cake III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 7), "Packed Cake IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 8), "Packed Carrots I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 9), "Packed Carrots II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 10), "Packed Carrots III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 11), "Packed Carrots IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 12), "Packed Golden Carrots I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 13), "Packed Golden Carrots II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 14), "Packed Golden Carrots III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodII, 1, 15), "Packed Golden Carrots IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 0), "Packed Raw Chicken I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 1), "Packed Raw Chicken II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 2), "Packed Raw Chicken III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 3), "Packed Raw Chicken IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 4), "Packed Cooked Chicken I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 5), "Packed Cooked Chicken II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 6), "Packed Cooked Chicken III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 7), "Packed Cooked Chicken IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 8), "Packed Cookies I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 9), "Packed Cookies II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 10), "Packed Cookies III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 11), "Packed Cookies IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 12), "Packed Eggs I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 13), "Packed Eggs II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 14), "Packed Eggs III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIII, 1, 15), "Packed Eggs IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 0), "Packed Sugar I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 1), "Packed Sugar II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 2), "Packed Sugar III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 3), "Packed Sugar IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 4), "Packed Potato I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 5), "Packed Potato II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 6), "Packed Potato III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 7), "Packed Potato IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 8), "Packed Baked Potato I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 9), "Packed Baked Potato II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 10), "Packed Baked Potato III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 11), "Packed Baked Potato IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 12), "Packed Poisoned Potato I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 13), "Packed Poisoned Potato II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 14), "Packed Poisoned Potato III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodIV, 1, 15), "Packed Poisoned Potato IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 0), "Packed Raw Fish I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 1), "Packed Raw Fish II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 2), "Packed Raw Fish III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 3), "Packed Raw Fish IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 4), "Packed Cooked Fish I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 5), "Packed Cooked Fish II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 6), "Packed Cooked Fish III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 7), "Packed Cooked Fish IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 8), "Packed Raw Pork I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 9), "Packed Raw Pork II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 10), "Packed Raw Pork III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 11), "Packed Raw Pork IV");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 12), "Packed Cooked Pork I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 13), "Packed Cooked Pork II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 14), "Packed Cooked Pork III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.packedfoodV, 1, 15), "Packed Cooked Pork IV");
        
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedWoodPickaxeI), "Hardened Wood Pickaxe I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedWoodPickaxeII), "Hardened Wood Pickaxe II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedWoodPickaxeIII), "Hardened Wood Pickaxe III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedWoodPickaxeIV), "Hardened Wood Pickaxe IV");        
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedStonePickaxeI), "Hardened Stone Pickaxe I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedStonePickaxeII), "Hardened Stone Pickaxe II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedStonePickaxeIII), "Hardened Stone Pickaxe III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedStonePickaxeIV), "Hardened Stone Pickaxe IV");        
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedIronPickaxeI), "Hardened Iron Pickaxe I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedIronPickaxeII), "Hardened Iron Pickaxe II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedIronPickaxeIII), "Hardened Iron Pickaxe III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedIronPickaxeIV), "Hardened Iron Pickaxe IV");      
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedGoldPickaxeI), "Hardened Gold Pickaxe I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedGoldPickaxeII), "Hardened Gold Pickaxe II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedGoldPickaxeIII), "Hardened Gold Pickaxe III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedGoldPickaxeIV), "Hardened Gold Pickaxe IV");      
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedDiamondPickaxeI), "Hardened Diamond Pickaxe I");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedDiamondPickaxeII), "Hardened Diamond Pickaxe II");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedDiamondPickaxeIII), "Hardened Diamond Pickaxe III");
        LanguageRegistry.instance().addName(new ItemStack(StoreMore.hardenedDiamondPickaxeIV), "Hardened Diamond Pickaxe IV");

    }
		
}
