package mods.storemore;

import mods.storemore.ic2.api.Items;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import cpw.mods.fml.common.registry.GameRegistry;

public class sm_recipes extends StoreMore{
	public static void initRecipes()
		

		{

		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.cobblestone));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,3));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.stone));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,11));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,12));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,13));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksI,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,14));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.dirt));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,3));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.gravel));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,11));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,12));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,13));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksII,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,14));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.sand));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,3));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.sandStone));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,11));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,12));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,13));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIII,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,14));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIV,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.obsidian));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIV,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIV,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIV,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIV,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.glowStone));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIV,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIV,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIV,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIV,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.netherrack));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIV,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIV,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIV,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedglass,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.glass));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedglass,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedglass,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedglass,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedglass,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedglass,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedglass,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.blockSteel));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.blockGold));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.blockDiamond));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.blockEmerald));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,12));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,13));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksV,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,14));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedcoalI,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.coal));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedcoalII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.packedcoalI,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedcoalIII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.packedcoalII,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedcoalIV,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.packedcoalIII,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedcharcoalI,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.coal,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedcharcoalII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.packedcharcoalI,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedcharcoalIII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.packedcharcoalII,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedcharcoalIV,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.packedcharcoalIII,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.stick));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.torchWood));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.gunpowder));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.flint));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,12));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,13));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVI,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,14));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.wood));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.wood,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.wood,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.wood,1,3));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,12));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,13));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVII,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,14));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.planks));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.planks,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.planks,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.planks,1,3));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,12));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,13));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksVIII,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,14));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.blockRedstone));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIX,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIX,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIX,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.blockNetherQuartz));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIX,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIX,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIX,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.slowSand));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIX,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIX,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIX,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.clay));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIX,1,12));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIX,1,13));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedblocksIX,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIX,1,14));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.appleRed));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodI,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodI,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodI,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.appleGold));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodI,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodI,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodI,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.beefRaw));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodI,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodI,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodI,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.beefCooked));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodI,1,12));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodI,1,13));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodI,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodI,1,14));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.bread));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodII,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodII,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodII,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.cake));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodII,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodII,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodII,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.carrot));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodII,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodII,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodII,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.goldenCarrot));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodII,1,12));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodII,1,13));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodII,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodII,1,14));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.chickenRaw));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIII,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIII,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIII,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.chickenCooked));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIII,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIII,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIII,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.cookie));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIII,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIII,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIII,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.egg));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIII,1,12));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIII,1,13));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIII,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIII,1,14));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.sugar));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIV,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIV,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIV,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.potato));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIV,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIV,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIV,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.bakedPotato));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIV,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIV,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIV,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.poisonousPotato));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIV,1,12));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIV,1,13));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodIV,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodIV,1,14));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.fishRaw));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodV,1,0));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodV,1,1));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodV,1,2));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.fishCooked));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodV,1,4));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodV,1,5));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodV,1,6));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.porkRaw));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodV,1,8));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodV,1,9));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodV,1,10));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.porkCooked));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodV,1,12));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodV,1,13));
		GameRegistry.addRecipe(new ItemStack(StoreMore.packedfoodV,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedfoodV,1,14));
		

		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedWoodPickaxeI), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.pickaxeWood));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedWoodPickaxeII), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedWoodPickaxeI));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedWoodPickaxeIII), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedWoodPickaxeII));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedWoodPickaxeIV), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedWoodPickaxeIII));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedStonePickaxeI), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.pickaxeStone));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedStonePickaxeII), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedStonePickaxeI));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedStonePickaxeIII), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedStonePickaxeII));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedStonePickaxeIV), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedStonePickaxeIII));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedIronPickaxeI), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.pickaxeSteel));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedIronPickaxeII), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedIronPickaxeI));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedIronPickaxeIII), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedIronPickaxeII));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedIronPickaxeIV), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedIronPickaxeIII));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedGoldPickaxeI), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.pickaxeGold));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedGoldPickaxeII), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedGoldPickaxeI));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedGoldPickaxeIII), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedGoldPickaxeII));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedGoldPickaxeIV), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedGoldPickaxeIII));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedDiamondPickaxeI), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.pickaxeDiamond));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedDiamondPickaxeII), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedDiamondPickaxeI));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedDiamondPickaxeIII), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedDiamondPickaxeII));
		GameRegistry.addRecipe(new ItemStack(StoreMore.hardenedDiamondPickaxeIV), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(StoreMore.hardenedDiamondPickaxeIII));

			//Unpacking
		GameRegistry.addShapelessRecipe(new ItemStack(Block.cobblestone,9), new ItemStack(StoreMore.packedblocksI,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,0), new ItemStack(StoreMore.packedblocksI,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,1), new ItemStack(StoreMore.packedblocksI,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,2), new ItemStack(StoreMore.packedblocksI,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,3), new ItemStack(StoreMore.packedblocksI,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,4), new ItemStack(StoreMore.packedblocksI,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,5), new ItemStack(StoreMore.packedblocksI,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,6), new ItemStack(StoreMore.packedblocksI,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.stone,9), new ItemStack(StoreMore.packedblocksI,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,8), new ItemStack(StoreMore.packedblocksI,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,9), new ItemStack(StoreMore.packedblocksI,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,10), new ItemStack(StoreMore.packedblocksI,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,11), new ItemStack(StoreMore.packedblocksI,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,12), new ItemStack(StoreMore.packedblocksI,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,13), new ItemStack(StoreMore.packedblocksI,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksI,9,14), new ItemStack(StoreMore.packedblocksI,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.dirt,9), new ItemStack(StoreMore.packedblocksII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,0), new ItemStack(StoreMore.packedblocksII,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,1), new ItemStack(StoreMore.packedblocksII,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,2), new ItemStack(StoreMore.packedblocksII,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,3), new ItemStack(StoreMore.packedblocksII,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,4), new ItemStack(StoreMore.packedblocksII,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,5), new ItemStack(StoreMore.packedblocksII,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,6), new ItemStack(StoreMore.packedblocksII,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.gravel,9), new ItemStack(StoreMore.packedblocksII,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,8), new ItemStack(StoreMore.packedblocksII,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,9), new ItemStack(StoreMore.packedblocksII,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,10), new ItemStack(StoreMore.packedblocksII,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,11), new ItemStack(StoreMore.packedblocksII,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,12), new ItemStack(StoreMore.packedblocksII,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,13), new ItemStack(StoreMore.packedblocksII,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksII,9,14), new ItemStack(StoreMore.packedblocksII,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.sand,9), new ItemStack(StoreMore.packedblocksIII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,0), new ItemStack(StoreMore.packedblocksIII,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,1), new ItemStack(StoreMore.packedblocksIII,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,2), new ItemStack(StoreMore.packedblocksIII,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,3), new ItemStack(StoreMore.packedblocksIII,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,4), new ItemStack(StoreMore.packedblocksIII,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,5), new ItemStack(StoreMore.packedblocksIII,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,6), new ItemStack(StoreMore.packedblocksIII,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.sandStone,9), new ItemStack(StoreMore.packedblocksIII,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,8), new ItemStack(StoreMore.packedblocksIII,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,9), new ItemStack(StoreMore.packedblocksIII,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,10), new ItemStack(StoreMore.packedblocksIII,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,11), new ItemStack(StoreMore.packedblocksIII,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,12), new ItemStack(StoreMore.packedblocksIII,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,13), new ItemStack(StoreMore.packedblocksIII,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIII,9,14), new ItemStack(StoreMore.packedblocksIII,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.obsidian,9), new ItemStack(StoreMore.packedblocksIV,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIV,9,0), new ItemStack(StoreMore.packedblocksIV,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIV,9,1), new ItemStack(StoreMore.packedblocksIV,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIV,9,2), new ItemStack(StoreMore.packedblocksIV,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.glowStone,9), new ItemStack(StoreMore.packedblocksIV,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIV,9,4), new ItemStack(StoreMore.packedblocksIV,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIV,9,5), new ItemStack(StoreMore.packedblocksIV,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIV,9,6), new ItemStack(StoreMore.packedblocksIV,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.netherrack,9), new ItemStack(StoreMore.packedblocksIV,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIV,9,8), new ItemStack(StoreMore.packedblocksIV,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIV,9,9), new ItemStack(StoreMore.packedblocksIV,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIV,9,10), new ItemStack(StoreMore.packedblocksIV,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.glass,9), new ItemStack(StoreMore.packedglass,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedglass,9,0), new ItemStack(StoreMore.packedglass,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedglass,9,1), new ItemStack(StoreMore.packedglass,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedglass,9,2), new ItemStack(StoreMore.packedglass,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.blockSteel,9), new ItemStack(StoreMore.packedblocksV,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksV,9,0), new ItemStack(StoreMore.packedblocksV,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksV,9,1), new ItemStack(StoreMore.packedblocksV,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksV,9,2), new ItemStack(StoreMore.packedblocksV,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.blockGold,9), new ItemStack(StoreMore.packedblocksV,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksV,9,4), new ItemStack(StoreMore.packedblocksV,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksV,9,5), new ItemStack(StoreMore.packedblocksV,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksV,9,6), new ItemStack(StoreMore.packedblocksV,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.blockDiamond,9), new ItemStack(StoreMore.packedblocksV,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksV,9,8), new ItemStack(StoreMore.packedblocksV,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksV,9,9), new ItemStack(StoreMore.packedblocksV,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksV,9,10), new ItemStack(StoreMore.packedblocksV,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.blockEmerald,9), new ItemStack(StoreMore.packedblocksV,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksV,9,12), new ItemStack(StoreMore.packedblocksV,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksV,9,13), new ItemStack(StoreMore.packedblocksV,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksV,9,14), new ItemStack(StoreMore.packedblocksV,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.coal,9), new ItemStack(StoreMore.packedcoalI,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedcoalI,9,0), new ItemStack(StoreMore.packedcoalII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedcoalII,9,0), new ItemStack(StoreMore.packedcoalIII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedcoalIII,9,0), new ItemStack(StoreMore.packedcoalIV,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.coal,9,1), new ItemStack(StoreMore.packedcharcoalI,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedcharcoalI,9,0), new ItemStack(StoreMore.packedcharcoalII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedcharcoalII,9,0), new ItemStack(StoreMore.packedcharcoalIII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedcharcoalIII,9,0), new ItemStack(StoreMore.packedcharcoalIV,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.stick,9), new ItemStack(StoreMore.packedblocksVI,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVI,9,0), new ItemStack(StoreMore.packedblocksVI,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVI,9,1), new ItemStack(StoreMore.packedblocksVI,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVI,9,2), new ItemStack(StoreMore.packedblocksVI,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.torchWood,9), new ItemStack(StoreMore.packedblocksVI,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVI,9,4), new ItemStack(StoreMore.packedblocksVI,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVI,9,5), new ItemStack(StoreMore.packedblocksVI,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVI,9,6), new ItemStack(StoreMore.packedblocksVI,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.gunpowder,9), new ItemStack(StoreMore.packedblocksVI,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVI,9,8), new ItemStack(StoreMore.packedblocksVI,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVI,9,9), new ItemStack(StoreMore.packedblocksVI,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVI,9,10), new ItemStack(StoreMore.packedblocksVI,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.flint,9), new ItemStack(StoreMore.packedblocksVI,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVI,9,12), new ItemStack(StoreMore.packedblocksVI,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVI,9,13), new ItemStack(StoreMore.packedblocksVI,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVI,9,14), new ItemStack(StoreMore.packedblocksVI,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.wood,9,0), new ItemStack(StoreMore.packedblocksVII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVII,9,0), new ItemStack(StoreMore.packedblocksVII,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVII,9,1), new ItemStack(StoreMore.packedblocksVII,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVII,9,2), new ItemStack(StoreMore.packedblocksVII,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.wood,9,1), new ItemStack(StoreMore.packedblocksVII,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVII,9,4), new ItemStack(StoreMore.packedblocksVII,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVII,9,5), new ItemStack(StoreMore.packedblocksVII,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVII,9,6), new ItemStack(StoreMore.packedblocksVII,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.wood,9,2), new ItemStack(StoreMore.packedblocksVII,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVII,9,8), new ItemStack(StoreMore.packedblocksVII,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVII,9,9), new ItemStack(StoreMore.packedblocksVII,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVII,9,10), new ItemStack(StoreMore.packedblocksVII,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.wood,9,3), new ItemStack(StoreMore.packedblocksVII,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVII,9,12), new ItemStack(StoreMore.packedblocksVII,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVII,9,13), new ItemStack(StoreMore.packedblocksVII,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVII,9,14), new ItemStack(StoreMore.packedblocksVII,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.planks,9,0), new ItemStack(StoreMore.packedblocksVIII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVIII,9,0), new ItemStack(StoreMore.packedblocksVIII,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVIII,9,1), new ItemStack(StoreMore.packedblocksVIII,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVIII,9,2), new ItemStack(StoreMore.packedblocksVIII,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.planks,9,1), new ItemStack(StoreMore.packedblocksVIII,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVIII,9,4), new ItemStack(StoreMore.packedblocksVIII,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVIII,9,5), new ItemStack(StoreMore.packedblocksVIII,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVIII,9,6), new ItemStack(StoreMore.packedblocksVIII,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.planks,9,2), new ItemStack(StoreMore.packedblocksVIII,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVIII,9,8), new ItemStack(StoreMore.packedblocksVIII,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVIII,9,9), new ItemStack(StoreMore.packedblocksVIII,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVIII,9,10), new ItemStack(StoreMore.packedblocksVIII,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.planks,9,3), new ItemStack(StoreMore.packedblocksVIII,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVIII,9,12), new ItemStack(StoreMore.packedblocksVIII,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVIII,9,13), new ItemStack(StoreMore.packedblocksVIII,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksVIII,9,14), new ItemStack(StoreMore.packedblocksVIII,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.blockRedstone,9,0), new ItemStack(StoreMore.packedblocksIX,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIX,9,0), new ItemStack(StoreMore.packedblocksIX,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIX,9,1), new ItemStack(StoreMore.packedblocksIX,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIX,9,2), new ItemStack(StoreMore.packedblocksIX,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.blockNetherQuartz,9,0), new ItemStack(StoreMore.packedblocksIX,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIX,9,4), new ItemStack(StoreMore.packedblocksIX,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIX,9,5), new ItemStack(StoreMore.packedblocksIX,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIX,9,6), new ItemStack(StoreMore.packedblocksIX,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.slowSand,9,0), new ItemStack(StoreMore.packedblocksIX,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIX,9,8), new ItemStack(StoreMore.packedblocksIX,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIX,9,9), new ItemStack(StoreMore.packedblocksIX,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIX,9,10), new ItemStack(StoreMore.packedblocksIX,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.clay,9,0), new ItemStack(StoreMore.packedblocksIX,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIX,9,12), new ItemStack(StoreMore.packedblocksIX,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIX,9,13), new ItemStack(StoreMore.packedblocksIX,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedblocksIX,9,14), new ItemStack(StoreMore.packedblocksIX,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.appleRed,9,0), new ItemStack(StoreMore.packedfoodI,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodI,9,0), new ItemStack(StoreMore.packedfoodI,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodI,9,1), new ItemStack(StoreMore.packedfoodI,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodI,9,2), new ItemStack(StoreMore.packedfoodI,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.appleGold,9,0), new ItemStack(StoreMore.packedfoodI,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodI,9,4), new ItemStack(StoreMore.packedfoodI,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodI,9,5), new ItemStack(StoreMore.packedfoodI,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodI,9,6), new ItemStack(StoreMore.packedfoodI,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.beefRaw,9,0), new ItemStack(StoreMore.packedfoodI,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodI,9,8), new ItemStack(StoreMore.packedfoodI,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodI,9,9), new ItemStack(StoreMore.packedfoodI,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodI,9,10), new ItemStack(StoreMore.packedfoodI,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.beefCooked,9,0), new ItemStack(StoreMore.packedfoodI,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodI,9,12), new ItemStack(StoreMore.packedfoodI,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodI,9,13), new ItemStack(StoreMore.packedfoodI,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodI,9,14), new ItemStack(StoreMore.packedfoodI,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.bread,9,0), new ItemStack(StoreMore.packedfoodII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodII,9,0), new ItemStack(StoreMore.packedfoodII,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodII,9,1), new ItemStack(StoreMore.packedfoodII,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodII,9,2), new ItemStack(StoreMore.packedfoodII,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.cake,9,0), new ItemStack(StoreMore.packedfoodII,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodII,9,4), new ItemStack(StoreMore.packedfoodII,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodII,9,5), new ItemStack(StoreMore.packedfoodII,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodII,9,6), new ItemStack(StoreMore.packedfoodII,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.carrot,9,0), new ItemStack(StoreMore.packedfoodII,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodII,9,8), new ItemStack(StoreMore.packedfoodII,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodII,9,9), new ItemStack(StoreMore.packedfoodII,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodII,9,10), new ItemStack(StoreMore.packedfoodII,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.goldenCarrot,9,0), new ItemStack(StoreMore.packedfoodII,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodII,9,12), new ItemStack(StoreMore.packedfoodII,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodII,9,13), new ItemStack(StoreMore.packedfoodII,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodII,9,14), new ItemStack(StoreMore.packedfoodII,1,15));     
		GameRegistry.addShapelessRecipe(new ItemStack(Item.chickenRaw,9,0), new ItemStack(StoreMore.packedfoodIII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIII,9,0), new ItemStack(StoreMore.packedfoodIII,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIII,9,1), new ItemStack(StoreMore.packedfoodIII,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIII,9,2), new ItemStack(StoreMore.packedfoodIII,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.chickenCooked,9,0), new ItemStack(StoreMore.packedfoodIII,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIII,9,4), new ItemStack(StoreMore.packedfoodIII,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIII,9,5), new ItemStack(StoreMore.packedfoodIII,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIII,9,6), new ItemStack(StoreMore.packedfoodIII,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.cookie,9,0), new ItemStack(StoreMore.packedfoodIII,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIII,9,8), new ItemStack(StoreMore.packedfoodIII,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIII,9,9), new ItemStack(StoreMore.packedfoodIII,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIII,9,10), new ItemStack(StoreMore.packedfoodIII,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.egg,9,0), new ItemStack(StoreMore.packedfoodIII,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIII,9,12), new ItemStack(StoreMore.packedfoodIII,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIII,9,13), new ItemStack(StoreMore.packedfoodIII,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIII,9,14), new ItemStack(StoreMore.packedfoodIII,1,15));     
		GameRegistry.addShapelessRecipe(new ItemStack(Item.sugar,9,0), new ItemStack(StoreMore.packedfoodIV,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIV,9,0), new ItemStack(StoreMore.packedfoodIV,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIV,9,1), new ItemStack(StoreMore.packedfoodIV,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIV,9,2), new ItemStack(StoreMore.packedfoodIV,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.potato,9,0), new ItemStack(StoreMore.packedfoodIV,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIV,9,4), new ItemStack(StoreMore.packedfoodIV,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIV,9,5), new ItemStack(StoreMore.packedfoodIV,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIV,9,6), new ItemStack(StoreMore.packedfoodIV,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.bakedPotato,9,0), new ItemStack(StoreMore.packedfoodIV,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIV,9,8), new ItemStack(StoreMore.packedfoodIV,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIV,9,9), new ItemStack(StoreMore.packedfoodIV,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIV,9,10), new ItemStack(StoreMore.packedfoodIV,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.poisonousPotato,9,0), new ItemStack(StoreMore.packedfoodIV,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIV,9,12), new ItemStack(StoreMore.packedfoodIV,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIV,9,13), new ItemStack(StoreMore.packedfoodIV,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodIV,9,14), new ItemStack(StoreMore.packedfoodIV,1,15));     
		GameRegistry.addShapelessRecipe(new ItemStack(Item.fishRaw,9,0), new ItemStack(StoreMore.packedfoodV,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodV,9,0), new ItemStack(StoreMore.packedfoodV,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodV,9,1), new ItemStack(StoreMore.packedfoodV,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodV,9,2), new ItemStack(StoreMore.packedfoodV,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.fishCooked,9,0), new ItemStack(StoreMore.packedfoodV,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodV,9,4), new ItemStack(StoreMore.packedfoodV,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodV,9,5), new ItemStack(StoreMore.packedfoodV,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodV,9,6), new ItemStack(StoreMore.packedfoodV,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.porkRaw,9,0), new ItemStack(StoreMore.packedfoodV,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodV,9,8), new ItemStack(StoreMore.packedfoodV,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodV,9,9), new ItemStack(StoreMore.packedfoodV,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodV,9,10), new ItemStack(StoreMore.packedfoodV,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.porkCooked,9,0), new ItemStack(StoreMore.packedfoodV,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodV,9,12), new ItemStack(StoreMore.packedfoodV,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodV,9,13), new ItemStack(StoreMore.packedfoodV,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(StoreMore.packedfoodV,9,14), new ItemStack(StoreMore.packedfoodV,1,15));           	
 
		}
	
}
	
	

	

