package mods.storemore;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import cpw.mods.fml.common.registry.GameRegistry;

public class sm_recipes extends storemoreMain{
	public static void initRecipes()
		

		{

		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.cobblestone));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,1));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,2));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,3));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,4));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,5));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,6));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.stone));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,8));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,9));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,10));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,11));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,12));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,13));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksI,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksI,1,14));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.dirt));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,1));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,2));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,3));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,4));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,5));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,6));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.gravel));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,8));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,9));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,10));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,11));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,12));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,13));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksII,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksII,1,14));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.sand));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,1));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,2));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,3));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,4));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,5));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,6));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.sandStone));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,8));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,9));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,10));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,11));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,12));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,13));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIII,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIII,1,14));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIV,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.obsidian));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIV,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIV,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,1));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIV,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,2));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIV,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.glowStone));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIV,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,4));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIV,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,5));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIV,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,6));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIV,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.netherrack));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIV,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,8));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIV,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,9));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksIV,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksIV,1,10));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedglass,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.glass));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedglass,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedglass,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedglass,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedglass,1,1));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedglass,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedglass,1,2));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.blockSteel));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,1));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,2));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.blockGold));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,4));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,5));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,6));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.blockDiamond));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,8));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,9));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,10));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.blockEmerald));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,12));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,13));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksV,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksV,1,14));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedcoalI,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.coal));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedcoalII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(storemoreMain.packedcoalI,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedcoalIII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(storemoreMain.packedcoalII,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedcoalIV,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(storemoreMain.packedcoalIII,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedcharcoalI,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.coal,1,1));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedcharcoalII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(storemoreMain.packedcharcoalI,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedcharcoalIII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(storemoreMain.packedcharcoalII,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedcharcoalIV,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(storemoreMain.packedcharcoalIII,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.stick));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,1));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,2));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.torchWood));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,4));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,5));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,6));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.gunpowder));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,8));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,9));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVI,1,10));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Item.flint));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,12));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,13));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVI,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,14));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.wood));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,1));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,2));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.wood,1,1));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,4));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,5));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,6));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.wood,1,2));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,8));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,9));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,10));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.wood,1,3));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,12));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,13));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVII,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVII,1,14));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,0), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.planks));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,1), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,0));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,2), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,1));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,3), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,2));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,4), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.planks,1,1));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,5), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,4));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,6), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,5));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,7), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,6));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,8), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.planks,1,2));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,9), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,8));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,10), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,9));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,11), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,10));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,12), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(Block.planks,1,3));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,13), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,12));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,14), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,13));
		GameRegistry.addRecipe(new ItemStack(storemoreMain.packedblocksVIII,1,15), "XXX", "XXX", "XXX", Character.valueOf('X'), new ItemStack(packedblocksVIII,1,14));

			//Unpacking
		GameRegistry.addShapelessRecipe(new ItemStack(Block.cobblestone,9), new ItemStack(storemoreMain.packedblocksI,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,0), new ItemStack(storemoreMain.packedblocksI,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,1), new ItemStack(storemoreMain.packedblocksI,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,2), new ItemStack(storemoreMain.packedblocksI,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,3), new ItemStack(storemoreMain.packedblocksI,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,4), new ItemStack(storemoreMain.packedblocksI,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,5), new ItemStack(storemoreMain.packedblocksI,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,6), new ItemStack(storemoreMain.packedblocksI,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.stone,9), new ItemStack(storemoreMain.packedblocksI,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,8), new ItemStack(storemoreMain.packedblocksI,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,9), new ItemStack(storemoreMain.packedblocksI,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,10), new ItemStack(storemoreMain.packedblocksI,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,11), new ItemStack(storemoreMain.packedblocksI,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,12), new ItemStack(storemoreMain.packedblocksI,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,13), new ItemStack(storemoreMain.packedblocksI,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksI,9,14), new ItemStack(storemoreMain.packedblocksI,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.dirt,9), new ItemStack(storemoreMain.packedblocksII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,0), new ItemStack(storemoreMain.packedblocksII,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,1), new ItemStack(storemoreMain.packedblocksII,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,2), new ItemStack(storemoreMain.packedblocksII,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,3), new ItemStack(storemoreMain.packedblocksII,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,4), new ItemStack(storemoreMain.packedblocksII,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,5), new ItemStack(storemoreMain.packedblocksII,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,6), new ItemStack(storemoreMain.packedblocksII,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.gravel,9), new ItemStack(storemoreMain.packedblocksII,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,8), new ItemStack(storemoreMain.packedblocksII,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,9), new ItemStack(storemoreMain.packedblocksII,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,10), new ItemStack(storemoreMain.packedblocksII,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,11), new ItemStack(storemoreMain.packedblocksII,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,12), new ItemStack(storemoreMain.packedblocksII,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,13), new ItemStack(storemoreMain.packedblocksII,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksII,9,14), new ItemStack(storemoreMain.packedblocksII,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.sand,9), new ItemStack(storemoreMain.packedblocksIII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,0), new ItemStack(storemoreMain.packedblocksIII,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,1), new ItemStack(storemoreMain.packedblocksIII,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,2), new ItemStack(storemoreMain.packedblocksIII,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,3), new ItemStack(storemoreMain.packedblocksIII,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,4), new ItemStack(storemoreMain.packedblocksIII,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,5), new ItemStack(storemoreMain.packedblocksIII,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,6), new ItemStack(storemoreMain.packedblocksIII,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.sandStone,9), new ItemStack(storemoreMain.packedblocksIII,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,8), new ItemStack(storemoreMain.packedblocksIII,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,9), new ItemStack(storemoreMain.packedblocksIII,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,10), new ItemStack(storemoreMain.packedblocksIII,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,11), new ItemStack(storemoreMain.packedblocksIII,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,12), new ItemStack(storemoreMain.packedblocksIII,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,13), new ItemStack(storemoreMain.packedblocksIII,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIII,9,14), new ItemStack(storemoreMain.packedblocksIII,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.obsidian,9), new ItemStack(storemoreMain.packedblocksIV,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIV,9,0), new ItemStack(storemoreMain.packedblocksIV,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIV,9,1), new ItemStack(storemoreMain.packedblocksIV,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIV,9,2), new ItemStack(storemoreMain.packedblocksIV,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.glowStone,9), new ItemStack(storemoreMain.packedblocksIV,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIV,9,4), new ItemStack(storemoreMain.packedblocksIV,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIV,9,5), new ItemStack(storemoreMain.packedblocksIV,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIV,9,6), new ItemStack(storemoreMain.packedblocksIV,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.netherrack,9), new ItemStack(storemoreMain.packedblocksIV,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIV,9,8), new ItemStack(storemoreMain.packedblocksIV,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIV,9,9), new ItemStack(storemoreMain.packedblocksIV,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksIV,9,10), new ItemStack(storemoreMain.packedblocksIV,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.glass,9), new ItemStack(storemoreMain.packedglass,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedglass,9,0), new ItemStack(storemoreMain.packedglass,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedglass,9,1), new ItemStack(storemoreMain.packedglass,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedglass,9,2), new ItemStack(storemoreMain.packedglass,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.blockSteel,9), new ItemStack(storemoreMain.packedblocksV,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksV,9,0), new ItemStack(storemoreMain.packedblocksV,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksV,9,1), new ItemStack(storemoreMain.packedblocksV,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksV,9,2), new ItemStack(storemoreMain.packedblocksV,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.blockGold,9), new ItemStack(storemoreMain.packedblocksV,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksV,9,4), new ItemStack(storemoreMain.packedblocksV,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksV,9,5), new ItemStack(storemoreMain.packedblocksV,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksV,9,6), new ItemStack(storemoreMain.packedblocksV,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.blockDiamond,9), new ItemStack(storemoreMain.packedblocksV,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksV,9,8), new ItemStack(storemoreMain.packedblocksV,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksV,9,9), new ItemStack(storemoreMain.packedblocksV,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksV,9,10), new ItemStack(storemoreMain.packedblocksV,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.blockEmerald,9), new ItemStack(storemoreMain.packedblocksV,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksV,9,12), new ItemStack(storemoreMain.packedblocksV,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksV,9,13), new ItemStack(storemoreMain.packedblocksV,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksV,9,14), new ItemStack(storemoreMain.packedblocksV,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.coal,9), new ItemStack(storemoreMain.packedcoalI,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedcoalI,9,0), new ItemStack(storemoreMain.packedcoalII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedcoalII,9,0), new ItemStack(storemoreMain.packedcoalIII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedcoalIII,9,0), new ItemStack(storemoreMain.packedcoalIV,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.coal,9,1), new ItemStack(storemoreMain.packedcharcoalI,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedcharcoalI,9,0), new ItemStack(storemoreMain.packedcharcoalII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedcharcoalII,9,0), new ItemStack(storemoreMain.packedcharcoalIII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedcharcoalIII,9,0), new ItemStack(storemoreMain.packedcharcoalIV,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.stick,9), new ItemStack(storemoreMain.packedblocksVI,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVI,9,0), new ItemStack(storemoreMain.packedblocksVI,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVI,9,1), new ItemStack(storemoreMain.packedblocksVI,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVI,9,2), new ItemStack(storemoreMain.packedblocksVI,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.torchWood,9), new ItemStack(storemoreMain.packedblocksVI,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVI,9,4), new ItemStack(storemoreMain.packedblocksVI,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVI,9,5), new ItemStack(storemoreMain.packedblocksVI,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVI,9,6), new ItemStack(storemoreMain.packedblocksVI,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.gunpowder,9), new ItemStack(storemoreMain.packedblocksVI,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVI,9,8), new ItemStack(storemoreMain.packedblocksVI,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVI,9,9), new ItemStack(storemoreMain.packedblocksVI,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVI,9,10), new ItemStack(storemoreMain.packedblocksVI,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Item.flint,9), new ItemStack(storemoreMain.packedblocksVI,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVI,9,12), new ItemStack(storemoreMain.packedblocksVI,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVI,9,13), new ItemStack(storemoreMain.packedblocksVI,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVI,9,14), new ItemStack(storemoreMain.packedblocksVI,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.wood,9,0), new ItemStack(storemoreMain.packedblocksVII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVII,9,0), new ItemStack(storemoreMain.packedblocksVII,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVII,9,1), new ItemStack(storemoreMain.packedblocksVII,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVII,9,2), new ItemStack(storemoreMain.packedblocksVII,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.wood,9,1), new ItemStack(storemoreMain.packedblocksVII,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVII,9,4), new ItemStack(storemoreMain.packedblocksVII,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVII,9,5), new ItemStack(storemoreMain.packedblocksVII,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVII,9,6), new ItemStack(storemoreMain.packedblocksVII,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.wood,9,2), new ItemStack(storemoreMain.packedblocksVII,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVII,9,8), new ItemStack(storemoreMain.packedblocksVII,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVII,9,9), new ItemStack(storemoreMain.packedblocksVII,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVII,9,10), new ItemStack(storemoreMain.packedblocksVII,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.wood,9,3), new ItemStack(storemoreMain.packedblocksVII,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVII,9,12), new ItemStack(storemoreMain.packedblocksVII,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVII,9,13), new ItemStack(storemoreMain.packedblocksVII,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVII,9,14), new ItemStack(storemoreMain.packedblocksVII,1,15));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.planks,9,0), new ItemStack(storemoreMain.packedblocksVIII,1,0));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVIII,9,0), new ItemStack(storemoreMain.packedblocksVIII,1,1));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVIII,9,1), new ItemStack(storemoreMain.packedblocksVIII,1,2));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVIII,9,2), new ItemStack(storemoreMain.packedblocksVIII,1,3));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.planks,9,1), new ItemStack(storemoreMain.packedblocksVIII,1,4));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVIII,9,4), new ItemStack(storemoreMain.packedblocksVIII,1,5));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVIII,9,5), new ItemStack(storemoreMain.packedblocksVIII,1,6));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVIII,9,6), new ItemStack(storemoreMain.packedblocksVIII,1,7));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.planks,9,2), new ItemStack(storemoreMain.packedblocksVIII,1,8));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVIII,9,8), new ItemStack(storemoreMain.packedblocksVIII,1,9));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVIII,9,9), new ItemStack(storemoreMain.packedblocksVIII,1,10));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVIII,9,10), new ItemStack(storemoreMain.packedblocksVIII,1,11));
		GameRegistry.addShapelessRecipe(new ItemStack(Block.planks,9,3), new ItemStack(storemoreMain.packedblocksVIII,1,12));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVIII,9,12), new ItemStack(storemoreMain.packedblocksVIII,1,13));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVIII,9,13), new ItemStack(storemoreMain.packedblocksVIII,1,14));
		GameRegistry.addShapelessRecipe(new ItemStack(storemoreMain.packedblocksVIII,9,14), new ItemStack(storemoreMain.packedblocksVIII,1,15));

	  }
	
}
