package mods.storemore;

import net.minecraft.item.ItemStack;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class sm_naming extends storemoreMain{
	
	public static void initNaming(){
	}

		public void loadNames()
		{
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 0), "Packed Cobblestone I");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 1),  "Packed Cobblestone II");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 2), "Packed Cobblestone III");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 3), "Packed Cobblestone IV");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 4), "Packed Cobblestone V");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 5), "Packed Cobblestone VI");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 6),  "Packed Cobblestone VII");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 7), "Packed Cobblestone VIII");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 8), "Packed Stone I");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 9), "Packed Stone II");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 10), "Packed Stone III");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 11), "Packed Stone IV");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 12), "Packed Stone V");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 13), "Packed Stone VI");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 14), "Packed Stone VII");
			 LanguageRegistry.addName(new ItemStack(packedblocksI, 1, 15), "Packed Stone VIII");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.dirtI.name", "Packed Dirt I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.dirtII.name", "Packed Dirt II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.dirtIII.name", "Packed Dirt III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.dirtIV.name", "Packed Dirt IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.dirtV.name", "Packed Dirt V");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.dirtVI.name", "Packed Dirt VI");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.dirtVII.name", "Packed Dirt VII");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.dirtVIII.name", "Packed Dirt VIII");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.gravelI.name", "Packed Gravel I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.gravelII.name", "Packed Gravel II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.gravelIII.name", "Packed Gravel III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.gravelIV.name", "Packed Gravel IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.gravelV.name", "Packed Gravel V");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.gravelVI.name", "Packed Gravel VI");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.gravelVII.name", "Packed Gravel VII");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksII.gravelVIII.name", "Packed Gravel VIII");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandI.name", "Packed Sand I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandII.name", "Packed Sand II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandIII.name", "Packed Sand III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandIV.name", "Packed Sand IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandV.name", "Packed Sand V");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandVI.name", "Packed Sand VI");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandVII.name", "Packed Sand VII");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandVIII.name", "Packed Sand VIII");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandstoneI.name", "Packed Sandstone I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandstoneII.name", "Packed Sandstone II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandstoneIII.name", "Packed Sandstone III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandstoneIV.name", "Packed Sandstone IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandstoneV.name", "Packed Sandstone V");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandstoneVI.name", "Packed Sandstone VI");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandstoneVII.name", "Packed Sandstone VII");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIII.sandstoneVIII.name", "Packed Sandstone VIII");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIV.obsidianI.name", "Packed Obsidian I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIV.obsidianII.name", "Packed Obsidian II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIV.obsidianIII.name", "Packed Obsidian III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIV.obsidianIV.name", "Packed Obsidian IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIV.netherrackI.name", "Packed Glowstone I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIV.netherrackII.name", "Packed Glowstone II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIV.netherrackIII.name", "Packed Glowstone III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIV.netherrackIV.name", "Packed Glowstone IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIV.glowstoneI.name", "Packed Netherrack I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIV.glowstoneII.name", "Packed Netherrack II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIV.glowstoneIII.name", "Packed Netherrack III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksIV.glowstoneIV.name", "Packed Netherrack IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedglass.glassI.name", "Packed Glass I");
		LanguageRegistry.instance().addStringLocalization("tile.packedglass.glassII.name", "Packed Glass II");
		LanguageRegistry.instance().addStringLocalization("tile.packedglass.glassIII.name", "Packed Glass III");
		LanguageRegistry.instance().addStringLocalization("tile.packedglass.glassIV.name", "Packed Glass IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.ironI.name", "Packed Iron I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.ironII.name", "Packed Iron II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.ironIII.name", "Packed Iron III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.ironIV.name", "Packed Iron IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.goldI.name", "Packed Gold I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.goldII.name", "Packed Gold II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.goldIII.name", "Packed Gold III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.goldIV.name", "Packed Gold IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.diamondI.name", "Packed Diamond I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.diamondII.name", "Packed Diamond II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.diamondIII.name", "Packed Diamond III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.diamondIV.name", "Packed Diamond IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.emeraldI.name", "Packed Emerald I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.emeraldII.name", "Packed Emerald II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.emeraldIII.name", "Packed Emerald III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksV.emeraldIV.name", "Packed Emerald IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedcoalI.coalI.name", "Packed Coal I");
		LanguageRegistry.instance().addStringLocalization("tile.packedcoalII.coalII.name", "Packed Coal II");
		LanguageRegistry.instance().addStringLocalization("tile.packedcoalIII.coalIII.name", "Packed Coal III");
		LanguageRegistry.instance().addStringLocalization("tile.packedcoalIV.coalIV.name", "Packed Coal IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedcharcoalI.charcoalI.name", "Packed Charcoal I");
		LanguageRegistry.instance().addStringLocalization("tile.packedcharcoalII.charcoalII.name", "Packed Charcoal II");
		LanguageRegistry.instance().addStringLocalization("tile.packedcharcoalIII.charcoalIII.name", "Packed Charcoal III");
		LanguageRegistry.instance().addStringLocalization("tile.packedcharcoalIV.charcoalIV.name", "Packed Charcoal IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.sticksI.name", "Packed Sticks I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.sticksII.name", "Packed Sticks II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.sticksIII.name", "Packed Sticks III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.sticksIV.name", "Packed Sticks IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.torchesI.name", "Packed Torches I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.torchesII.name", "Packed Torches II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.torchesIII.name", "Packed Torches III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.torchesIV.name", "Packed Torches IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.gunpowderI.name", "Packed Gunpowder I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.gunpowderII.name", "Packed Gunpowder II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.gunpowderIII.name", "Packed Gunpowder III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.gunpowderIV.name", "Packed Gunpowder IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.flintI.name", "Packed Flint I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.flintII.name", "Packed Flint II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.flintIII.name", "Packed Flint III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVI.flintIV.name", "Packed Flint IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.oakwoodI.name", "Packed Oak Wood I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.oakwoodII.name", "Packed Oak Wood II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.oakwoodIII.name", "Packed Oak Wood III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.oakwoodIV.name", "Packed Oak Wood IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.sprucewoodI.name", "Packed Spruce Wood I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.sprucewoodII.name", "Packed Spruce Wood II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.sprucewoodIII.name", "Packed Spruce Wood III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.sprucewoodIV.name", "Packed Spruce Wood IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.birchwoodI.name", "Packed Birch Wood I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.birchwoodII.name", "Packed Birch Wood II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.birchwoodIII.name", "Packed Birch Wood III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.birchwoodIV.name", "Packed Birch Wood IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.junglewoodI.name", "Packed Jungle Wood I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.junglewoodII.name", "Packed Jungle Wood II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.junglewoodIII.name", "Packed Jungle Wood III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVII.junglewoodIV.name", "Packed Jungle Wood IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.oakplanksI.name", "Packed Oak Planks I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.oakplanksII.name", "Packed Oak Planks II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.oakplanksIII.name", "Packed Oak Planks III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.oakplanksIV.name", "Packed Oak Planks IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.spruceplanksI.name", "Packed Spruce Planks I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.spruceplanksII.name", "Packed Spruce Planks II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.spruceplanksIII.name", "Packed Spruce Planks III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.spruceplanksIV.name", "Packed Spruce Planks IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.birchplanksI.name", "Packed Birch Planks I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.birchplanksII.name", "Packed Birch Planks II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.birchplanksIII.name", "Packed Birch Planks III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.birchplanksIV.name", "Packed Birch Planks IV");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.jungleplanksI.name", "Packed Jungle Planks I");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.jungleplanksII.name", "Packed Jungle Planks II");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.jungleplanksIII.name", "Packed Jungle Planks III");
		LanguageRegistry.instance().addStringLocalization("tile.packedblocksVIII.jungleplanksIV.name", "Packed Jungle Planks IV");

		}
		
	}
